In [1]:
import numpy as np

In [2]:
# np.linalg.

In [3]:
import scipy as sp

In [4]:
A = np.array([[1.0,1.0,-1.0],[3.0,-1.0,1.0],[1.0, -3.0,2.0]])
A

array([[ 1.,  1., -1.],
       [ 3., -1.,  1.],
       [ 1., -3.,  2.]])

In [5]:
b = np.array([[0],[4],[1.1]],dtype=float)
b

array([[0. ],
       [4. ],
       [1.1]])

In [6]:
np.linalg.solve(A,b)

array([[1. ],
       [1.9],
       [2.9]])

In [7]:
C = np.array([[1,1],[1.00001,1]],dtype=float)
d = np.array([2,2.0],dtype=float)

In [8]:
np.linalg.solve(C,d)

array([0., 2.])

In [9]:
np.linalg.cond(A,p = np.inf)

np.float64(24.0)

In [10]:
np.linalg.cond(C,p=np.inf)
# np.linalg.cond(C)

np.float64(400004.000007742)